import { Upload, ShieldAlert } from 'lucide-react';
import { useState } from 'react';
import FileUpload from './FileUpload';

export default function EmptyState() {
  const [showUpload, setShowUpload] = useState(false);
  return (
    <div className="flex flex-col items-center justify-center h-full gap-8 py-16">
      <div className="relative">
        <div className="w-24 h-24 rounded-full bg-cyber-card border border-cyber-cyan/20 flex items-center justify-center shadow-glow">
          <ShieldAlert size={40} className="text-cyber-cyan opacity-80" />
        </div>
        <div className="absolute -bottom-1 -right-1 w-8 h-8 rounded-full bg-cyber-surface border border-cyber-border flex items-center justify-center">
          <Upload size={14} className="text-slate-400" />
        </div>
      </div>

      <div className="text-center">
        <h2 className="text-xl font-semibold text-slate-200">No extract loaded</h2>
        <p className="text-slate-500 text-sm mt-2 max-w-xs">
          Upload one or more <span className="font-mono text-cyber-cyan">vulnerability_extract_*.csv</span> files generated by <span className="font-mono text-cyber-cyan">cx_extract.py</span>
        </p>
      </div>

      {showUpload ? (
        <div className="w-full max-w-md cyber-card p-6">
          <FileUpload onClose={() => setShowUpload(false)} />
        </div>
      ) : (
        <button
          onClick={() => setShowUpload(true)}
          className="flex items-center gap-2 px-5 py-2.5 bg-cyber-cyan/10 hover:bg-cyber-cyan/20 border border-cyber-cyan/30 text-cyber-cyan rounded-lg text-sm font-medium transition-all duration-150 shadow-glow-sm"
        >
          <Upload size={16} />
          Load extract files
        </button>
      )}
    </div>
  );
}
